# Generated by Django 2.1.2 on 2020-10-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Declaracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('apellido_pat', models.CharField(default='', max_length=100)),
                ('apellido_mat', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField(blank=True, null=True)),
                ('opinion', models.CharField(blank=True, choices=[('1', ' 1'), ('2', ' 2'), ('3', ' 3'), ('4', ' 4'), ('5', ' 5')], default='2', max_length=100, null=True)),
                ('declaracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Declaracion.Declaracion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicion.Alumno')),
            ],
        ),
    ]
