# Generated by Django 2.1.2 on 2020-10-30 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medicion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='declaracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Declaracion.Declaracion'),
        ),
    ]
