# Generated by Django 2.1.2 on 2020-10-31 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicion', '0002_auto_20201029_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicion',
            name='peso',
        ),
    ]
