# Generated by Django 2.1.2 on 2020-10-31 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medicion', '0003_remove_medicion_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prom_c1', models.IntegerField()),
                ('prom_c2', models.IntegerField()),
                ('prom_c3', models.IntegerField()),
                ('prom_c4', models.IntegerField()),
                ('prom_c5', models.IntegerField()),
                ('prom_c6', models.IntegerField()),
                ('prom_c7', models.IntegerField()),
                ('prom_c8', models.IntegerField()),
                ('prom_c9', models.IntegerField()),
                ('prom_c10', models.IntegerField()),
                ('ac1', models.IntegerField()),
                ('ac2', models.IntegerField()),
                ('ac3', models.IntegerField()),
                ('ac4', models.IntegerField()),
                ('factor_innovacion', models.IntegerField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicion.Alumno')),
            ],
        ),
    ]
