# Generated by Django 2.1.2 on 2020-11-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicion', '0004_calculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculo',
            name='alumno',
        ),
        migrations.DeleteModel(
            name='Calculo',
        ),
    ]
