# Generated by Django 2.1.2 on 2020-11-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicion', '0005_auto_20201102_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='factor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
