# Generated by Django 2.1.2 on 2020-11-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicion', '0006_medicion_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicion',
            name='factor',
        ),
    ]
