# Generated by Django 2.1.2 on 2020-11-03 19:00

import Medicion.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
        ('Medicion', '0007_remove_medicion_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Principal.Carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='alumno',
            name='rut',
            field=models.CharField(default='', max_length=13, validators=[Medicion.validators.digito_verificador]),
        ),
    ]
