# Generated by Django 2.1.2 on 2020-11-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medicion', '0008_auto_20201103_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mediciongrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(default='', max_length=254)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicion.Grupo')),
                ('integrante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicion.Alumno')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='integrante',
            field=models.ManyToManyField(blank=True, related_name='Mediciongrupo', through='Medicion.Mediciongrupo', to='Medicion.Alumno'),
        ),
    ]
